# Generated by Django 3.1.7 on 2021-04-19 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('page_keywords', models.CharField(blank=True, max_length=1024, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=128, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('page_keywords', models.CharField(blank=True, max_length=1024, null=True)),
                ('page_h1', models.CharField(blank=True, max_length=128, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('short_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('long_description', models.CharField(blank=True, max_length=4096, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
                ('categories', models.ManyToManyField(to='core.Category')),
                ('images', models.ManyToManyField(to='core.Image')),
                ('main_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='core.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuickReferenceCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=4096)),
                ('order', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=36, null=True)),
                ('email', models.CharField(blank=True, max_length=36, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=4096)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
