# Generated by Django 3.1.7 on 2021-03-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(max_length=1024)),
                ('created_datetime', models.DateTimeField()),
            ],
        ),
    ]
