# Generated by Django 3.1.7 on 2021-03-21 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210322_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 22, 42, 44, 480381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 22, 42, 44, 480857, tzinfo=utc)),
        ),
    ]
