# Generated by Django 3.1.7 on 2021-03-24 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210322_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=4096)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
