# Generated by Django 3.1.7 on 2021-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210425_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='no_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='no_index',
            field=models.BooleanField(default=False),
        ),
    ]
