# Generated by Django 3.1.7 on 2021-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210429_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.CharField(default='common', max_length=32),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
