# Generated by Django 3.1.7 on 2021-03-24 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
