# Generated by Django 3.1.7 on 2021-05-31 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210429_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('mobile', models.CharField(blank=True, max_length=36, null=True)),
                ('email', models.CharField(blank=True, max_length=36, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_id', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
    ]
