# Generated by Django 3.1.7 on 2021-03-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_social_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='url',
            new_name='action',
        ),
    ]
