# Generated by Django 3.1.7 on 2021-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210327_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
