# Generated by Django 3.1.7 on 2021-04-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210402_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='comment',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='email',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='mobile',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
