# Generated by Django 3.1.7 on 2021-04-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210406_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
