# Generated by Django 3.1.7 on 2021-04-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210406_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='page_description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='page_keywords',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='page_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_keywords',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
