# Generated by Django 3.1.7 on 2021-04-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210408_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_h1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_h1',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
