# Generated by Django 3.1.7 on 2021-04-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210410_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='main_image',
            new_name='product',
        ),
    ]
